---
title: "River Thames conditions at Hampton Court"
date: now
date-format: "YYYY-MM-DD HH:mm:ssZ"
toc: true
echo: false
jupyter: python3
reference-location: margin
format: 
    html:
        theme: lumen
        font-size: 0.8em
---

```{python}
#| echo: false
import hcc as hcc
from itables import init_notebook_mode, show, JavascriptFunction
init_notebook_mode()

```

## Times of sunrise and sunset

```{python}
hcc.sunrise_times()
```

## River conditions

::: column-margin
This river conditions information is from <https://www.gov.uk/guidance/river-thames-current-river-conditions> and gets updated at 5am every day.
:::

```{python}
import hcc as hcc
df = hcc.scrape_conditions()
show(
    df,  
    search={"search": "Local"},
    columnDefs = [{
        "targets": "_all",
        "createdCell": JavascriptFunction(
            """
            function (td, cellData, rowData, row, col) {
                let text = cellData.toLowerCase();
                if (text.includes("red caution")) {$(td).css('background-color', 'red').css('color', 'white');}
                if (text.includes("yellow caution")) {$(td).css('background-color', '#FFE010');}
            }
            """
            )
        }]
    )
```

## River flow rate

::: column-margin
Flow rate is the volume of water passing a point in a river per unit time. It is measured in cubic metres per second (m3/s), also known as Cumecs.

A flow rate of about **100 cumecs** at Walton seems to be the range when **yellow caution** (stream increasing) appear, and higher than **150 cumecs** when the **red caution** (strong stream) appear.
:::

```{=HTML}
<!-- Force plotly to recompute layout if a new panel tab is active -->
<!-- adapted from https://stackoverflow.com/a/62572610/602276 -->
<script type="text/javascript" charset="utf-8">
$(document).on('shown.bs.tab', function (event) {
    console.log("Tab shown");
    var doc = $(".tab-pane.active .plotly-graph-div");
    for (var i = 0; i < doc.length; i++) {
        _Plotly.relayout(doc[i], {autosize: true});
    }
});
</script>
```



::: panel-tabset
### Walton

```{python}
# from importlib import reload
# reload(hcc)
# compute today - 7 days
from datetime import datetime, timedelta
today = datetime.now()
seven = today - timedelta(days = 7)
seven = seven.date()

hcc.plot_thames_level("Walton", parameter = "flow", since = seven)
```

### Kingston

```{python}
hcc.plot_thames_level("Kingston", parameter = "flow", since = seven)
```
:::

## Water levels

::: panel-tabset
### Sunbury Lock

```{python}
hcc.plot_thames_level("Sunbury", position = "downstream", since = seven)
```

::: column-margin
What does the Sunbury lock water level mean at the club house?

5.05m : water lapping over step to club house, canoe drying area under water (all time peak reached on 2014-11-02)

4.95m : car park under water, canoe drying area a bit wet

4.50m : car park half under water, canoe drying area high and dry

4.00m : car park dry but river still in flood

3.19m : flooding possible in Sunbury

2.8m : river flow is strong, roughly 100 cumecs at Kingston, about the level where the yellow boards appear

2.4m : typical level when river flow is low
:::

### Molesey Lock

```{python}
# from importlib import reload
# import hcc
# reload(hcc)
# hcc.lookup_thames_station_name("Molesey Lock")

hcc.plot_thames_level("Molesey Lock", position = "downstream", since = seven)
```

### Richmond Lock

```{python}
hcc.plot_thames_level("Richmond", river_name = "Thames Tideway", since = seven)
```

### Richmond lock tide times

```{=html}
<script type="text/javascript" src="https://tidetimes.co.uk/widget?name=Richmond Lock&days=3"></script>
```
:::

## River closures and restrictions

::: column-margin
River closure information is collated from <https://www.gov.uk/guidance/river-thames-restrictions-and-closures> and is not guaranteed to be accurate or up-to-date.
:::

```{python}
df = hcc.scrape_river_closures()
show(df,  search={"search": "Local"})
```