# .github/workflows/render-and-publish.yaml
on:
  push:
  pull_request:

name: Render and deploy Quarto files

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Install python and restore venv"
        uses: actions/checkout@v3
        uses: actions/setup-python@v4

      - name: "Install Python"
        with:
          python-version: '3.10.5'
          cache: 'pip' # caching pip dependencies

      - name: "Install python deps"
        run: |
          pip install -r requirements.txt

      - name: "Install Quarto"
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Render Quarto Project"
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: thames-river-levels.qmd # By default, the current working dir is used i.e `quarto render .`

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
