# .github/workflows/render-and-publish.yaml
on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 6am every day
    - cron:  '0 5 * * *'

name: Render and deploy Quarto files

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
          cache: 'pip' # caching pip dependencies

      - name: "Install python deps"
        run: |
          pip install -r requirements.txt

      - name: "Install Quarto"
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.2.313

      - name: "Publish to quarto-pub"
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
          path: thames-river-levels.qmd
